# This is a basic workflow to help you get started with Actions

name: proofread

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  proofread:
    name: Proofread
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: place-labs/orthograph-err@master
